package proyectofinal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rodrigo Plauchu, Santiago Fernández, Daniel Barreto and Constanza Ybarra 
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
     * Método void que bloquea números y signos
     */
    void bloqueaNumYSig(){
        btMas.setEnabled(false);
        btMenos.setEnabled(false);
        btDiv.setEnabled(false);
        btMult.setEnabled(false);
        btIgual.setEnabled(false);
        btCambioSigno.setEnabled(true);
        btCerrarParentesis.setEnabled(false);
        btPunto.setEnabled(true);
    }
    /**
     * Método void que bloquea números y signos para la división
     */
    void bloqueaNumYSigDiv(){
        btMas.setEnabled(false);
        btMenos.setEnabled(false);
        btDiv.setEnabled(false);
        btMult.setEnabled(false);
        btIgual.setEnabled(false);
        btCambioSigno.setEnabled(true);
        btCerrarParentesis.setEnabled(false);
        btPunto.setEnabled(true);
        bt0.setEnabled(false);
    }
    /**
     * Método void que habilita números y signos
     */
    void HabilotaNumYSig(){
        btMas.setEnabled(true);
        btMenos.setEnabled(true);
        btDiv.setEnabled(true);
        btMult.setEnabled(true);
        btIgual.setEnabled(true);
        btCambioSigno.setEnabled(false);
        btCerrarParentesis.setEnabled(true);
    }
    /**
     * Método void que bloquea números y signos para el punto
     */
    void bloqueaNumYSigYPunto(){
        btMas.setEnabled(false);
        btMenos.setEnabled(false);
        btDiv.setEnabled(false);
        btMult.setEnabled(false);
        btIgual.setEnabled(false);
        btPunto.setEnabled(false);
        btCambioSigno.setEnabled(false);
        btCerrarParentesis.setEnabled(false);
    }
    /**
     * Método void que bloquea signos para el paréntesis
     */
    void bloqueaPorParentesis(){
        
        btIgual.setEnabled(false);
        btCerrarParentesis.setEnabled(false);
        btCambioSigno.setEnabled(false);
        btCerrarParentesis.setEnabled(false);
    }
    /**
     * Método void que habilita todo
     */
    void HabilitaTodo(){
        btMas.setEnabled(true);
        btMenos.setEnabled(true);
        btDiv.setEnabled(true);
        btMult.setEnabled(true);
        btIgual.setEnabled(true);
        btCambioSigno.setEnabled(true);
        btCerrarParentesis.setEnabled(true);
        btPunto.setEnabled(true);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btAbrirParentesis = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btCerrarParentesis = new javax.swing.JButton();
        btDiv = new javax.swing.JButton();
        btMenos = new javax.swing.JButton();
        btPunto = new javax.swing.JButton();
        btMas = new javax.swing.JButton();
        btCambioSigno = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        tfPantalla = new javax.swing.JTextField();
        btMult = new javax.swing.JButton();

        jButton14.setText(")");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(204, 0, 0));

        btLimpiar.setBackground(new java.awt.Color(255, 124, 0));
        btLimpiar.setText("C");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        bt7.setBackground(new java.awt.Color(0, 0, 0));
        bt7.setForeground(new java.awt.Color(255, 255, 255));
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(0, 0, 0));
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(0, 0, 0));
        bt8.setForeground(new java.awt.Color(255, 255, 255));
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        btAbrirParentesis.setBackground(new java.awt.Color(153, 153, 153));
        btAbrirParentesis.setForeground(new java.awt.Color(255, 255, 255));
        btAbrirParentesis.setText("(");
        btAbrirParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirParentesisActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(0, 0, 0));
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(0, 0, 0));
        bt9.setForeground(new java.awt.Color(255, 255, 255));
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(0, 0, 0));
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(0, 0, 0));
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt0.setBackground(new java.awt.Color(0, 0, 0));
        bt0.setForeground(new java.awt.Color(255, 255, 255));
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        btCerrarParentesis.setBackground(new java.awt.Color(153, 153, 153));
        btCerrarParentesis.setForeground(new java.awt.Color(255, 255, 255));
        btCerrarParentesis.setText(")");
        btCerrarParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarParentesisActionPerformed(evt);
            }
        });

        btDiv.setBackground(new java.awt.Color(255, 102, 0));
        btDiv.setText("/");
        btDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivActionPerformed(evt);
            }
        });

        btMenos.setBackground(new java.awt.Color(255, 102, 0));
        btMenos.setText("-");
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });

        btPunto.setBackground(new java.awt.Color(0, 0, 0));
        btPunto.setForeground(new java.awt.Color(255, 255, 255));
        btPunto.setText(".");
        btPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPuntoActionPerformed(evt);
            }
        });

        btMas.setBackground(new java.awt.Color(255, 102, 0));
        btMas.setText("+");
        btMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMasActionPerformed(evt);
            }
        });

        btCambioSigno.setBackground(new java.awt.Color(255, 102, 0));
        btCambioSigno.setText(":");
        btCambioSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambioSignoActionPerformed(evt);
            }
        });

        btIgual.setBackground(new java.awt.Color(255, 102, 0));
        btIgual.setText("=");
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });

        tfPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPantallaActionPerformed(evt);
            }
        });

        btMult.setBackground(new java.awt.Color(255, 102, 0));
        btMult.setText("*");
        btMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt5)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt3)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btCambioSigno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt6)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btDiv, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt7)
                                    .addComponent(btLimpiar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAbrirParentesis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCerrarParentesis))
                            .addComponent(tfPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7)
                    .addComponent(bt9)
                    .addComponent(btMas)
                    .addComponent(bt8)
                    .addComponent(btMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt5)
                    .addComponent(bt6)
                    .addComponent(btDiv)
                    .addComponent(btMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt2)
                            .addComponent(bt3)
                            .addComponent(bt1)
                            .addComponent(btCambioSigno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAbrirParentesis)
                            .addComponent(bt0)
                            .addComponent(btCerrarParentesis)
                            .addComponent(btPunto)))
                    .addComponent(btIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Se mandan llamar los bloqueos por ser signo y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMasActionPerformed
        bloqueaNumYSig();
        String x;
        x=tfPantalla.getText();
        x=x+'+';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btMasActionPerformed
    /**
     * Se mandan llamar los bloqueos por ser signo y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
        bloqueaNumYSig();
        String x;
        x=tfPantalla.getText();
        x=x+'-';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btMenosActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"8";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt8ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"7";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt7ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"9";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt9ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"4";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt4ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"5";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt5ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"6";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt6ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       HabilotaNumYSig();
       String x;
	x=tfPantalla.getText();
	x=x+"1";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt1ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"2";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt2ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"3";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt3ActionPerformed
    /**
     * Manda llamar las habilitaciones de numeros y concatena caracteres
     * @param evt 
     */
    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        HabilotaNumYSig();
        String x;
	x=tfPantalla.getText();
	x=x+"0";
	tfPantalla.setText(x);
    }//GEN-LAST:event_bt0ActionPerformed
    /**
     * Se mandan llamar los bloqueos por ser signo y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivActionPerformed
        bloqueaNumYSig();
        String x;
        x=tfPantalla.getText();
        x=x+'/';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btDivActionPerformed
    /**
     * Se mandan llamar los bloqueos por ser signo y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultActionPerformed
        bloqueaNumYSig();
        String x;
        x=tfPantalla.getText();
        x=x+'*';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btMultActionPerformed
    /**
     * Se mandan llamar los bloqueos por ser signo y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btCambioSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambioSignoActionPerformed
         bloqueaNumYSig();
         btCambioSigno.setEnabled(false);
         String x;
         x=tfPantalla.getText();
         x=x+':';
	 tfPantalla.setText(x);
    }//GEN-LAST:event_btCambioSignoActionPerformed
    /**
     * Se mandan llamar los bloqueos especiales por ser paréntesis y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btAbrirParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirParentesisActionPerformed
        bloqueaPorParentesis();
        String x;
        x=tfPantalla.getText();
        x=x+'(';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btAbrirParentesisActionPerformed
    /**
     * Se mandan llamar los bloqueos por ser punto y concatena caracteres en la pantalla
     * @param evt 
     */
    private void btPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPuntoActionPerformed
        bloqueaNumYSigYPunto();
        String x;
        x=tfPantalla.getText();
        x=x+'.';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btPuntoActionPerformed
    /**
     * No necesitamos que haga nada la pantalla
     * @param evt 
     */
    private void tfPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPantallaActionPerformed
        
    }//GEN-LAST:event_tfPantallaActionPerformed
    /**
     * Limpia la pantalla y manda a llamar el método que activa todo
     * @param evt 
     */
    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        tfPantalla.setText("");
        HabilitaTodo();
    }//GEN-LAST:event_btLimpiarActionPerformed
    /**
     * No necesita bloqueos y concatena caracteres
     * @param evt 
     */
    private void btCerrarParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarParentesisActionPerformed
        String x;
        x=tfPantalla.getText();
        x=x+')';
	tfPantalla.setText(x);
    }//GEN-LAST:event_btCerrarParentesisActionPerformed
    /**
     * Transforma el string de la pantalla al resultado esperado
     * @param evt 
     */
    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        String x=tfPantalla.getText();
        String stringConvertido;
        
        
        if(ClasesPostFija.verificaLadosOperadores(x) && ClasesPostFija.verificarParentesis(x)){
            stringConvertido=ClasesPostFija.convertirPosfija(x);
            tfPantalla.setText(ClasesPostFija.calculaPostFija(stringConvertido)+"");
        }
        
    }//GEN-LAST:event_btIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
                
            }
        });
    }
    /**
     * 
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAbrirParentesis;
    private javax.swing.JButton btCambioSigno;
    private javax.swing.JButton btCerrarParentesis;
    private javax.swing.JButton btDiv;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btMas;
    private javax.swing.JButton btMenos;
    private javax.swing.JButton btMult;
    private javax.swing.JButton btPunto;
    private javax.swing.JButton jButton14;
    private javax.swing.JTextField tfPantalla;
    // End of variables declaration//GEN-END:variables
}
